Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade

     wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
     sudo dpkg -i packages-microsoft-prod.deb
     rm packages-microsoft-prod.deb

     sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
     sudo apt-get install -y git
     
     git clone https://github.com/evodev0101/CrossLabs.git
     cd CrossLabs/Lab5/Lab5
     dotnet run
  SHELL
end